package com.capp.batchcertcreator;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.Box;
import javax.swing.JButton;

/**
 *
 * @author mucahit.yilmaz
 */
public class DNCreatorPanel extends javax.swing.JPanel {

    private final Box container = Box.createVerticalBox();

    /**
     * Creates new form DNCreatorPanel
     */
    public DNCreatorPanel() {
        initComponents();
        add(container, BorderLayout.PAGE_START);
        NewRDNPanelAction newRDNPanelAction = new NewRDNPanelAction();
        newRDNPanelAction.actionPerformed(null);
        newRDNPanelAction.actionPerformed(null);
        newRDNPanelAction.actionPerformed(null);
        newRDNPanelAction.actionPerformed(null);
    }

    public String getSubject() {
        var subject = new StringBuilder();
        for (Component c : getComponents()) {
            RDNPanel panel = (RDNPanel) c;
            subject.append(panel.getRDNStringRepresentation());
        }
        return subject.substring(0, subject.length() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private class NewRDNPanelAction extends AbstractAction {

        public NewRDNPanelAction() {
            this.putValue(NAME, "+");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            var panel = new RDNPanel();
            panel.getNewBtn().setAction(new NewRDNPanelAction());
            panel.getRemoveBtn().setAction(new RemoveRDNPanelAction());
            container.add(panel);
            container.repaint();
            container.revalidate();
        }

    }

    private class RemoveRDNPanelAction extends AbstractAction {

        public RemoveRDNPanelAction() {
            this.putValue(NAME, "-");
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            JButton source = (JButton) e.getSource();
            Component component = source.getParent();
            container.remove(component);
            container.repaint();
            container.revalidate();
        }

    }
}
