package com.capp.batchcertcreator;

import javax.swing.JButton;

/**
 *
 * @author mucahit.yilmaz
 */
public class RDNPanel extends javax.swing.JPanel {

    /**
     * Creates new form RDNPanel
     */
    public RDNPanel() {
        initComponents();
    }

    public String getRDNStringRepresentation() {
        return rdnKeysCmb.getItemAt(rdnKeysCmb.getSelectedIndex()).getKey() + "=" + rdnValueTf.getText() + ",";
    }

    public JButton getNewBtn() {
        return newBtn;
    }

    public JButton getRemoveBtn() {
        return removeBtn;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdnKeysCmb = new javax.swing.JComboBox<>();
        rdnValueTf = new javax.swing.JTextField();
        newBtn = new javax.swing.JButton();
        removeBtn = new javax.swing.JButton();

        setName("Form"); // NOI18N

        rdnKeysCmb.setModel(com.capp.batchcertcreator.RDNKey.createComboboxModel());
        rdnKeysCmb.setName("rdnKeysCmb"); // NOI18N

        rdnValueTf.setName("rdnValueTf"); // NOI18N

        newBtn.setText("+"); // NOI18N
        newBtn.setName("newBtn"); // NOI18N

        removeBtn.setText("-"); // NOI18N
        removeBtn.setName("removeBtn"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdnKeysCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdnValueTf, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removeBtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdnKeysCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdnValueTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newBtn)
                    .addComponent(removeBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton newBtn;
    private javax.swing.JComboBox<com.capp.batchcertcreator.RDNKey> rdnKeysCmb;
    private javax.swing.JTextField rdnValueTf;
    private javax.swing.JButton removeBtn;
    // End of variables declaration//GEN-END:variables
}
